config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'
  resources :targets
  resources :divisions
  resources :teams
  resources :employees
  resources :users do
    member do
      delete :purge_picture
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'home/index'
  # get '/:locale' => 'home#index'
  root :to => "home#index"

end

app/models/employee.rb
class Employee < ApplicationRecord
  
    belongs_to :team, optional: true
    has_one :division, dependent: :nullify


    validates :email, presence: true, confirmation: true, uniqueness: true
    # validates :email_confirmation, presence: true

    validates :name,presence: true, format: { with: /\A[a-zA-Z]+\z/,
        message: "only allows letters" }
    
    validates :job, presence: true

    # validates :job,presence: true, format: { with: /\A[a-zA-Z ]+\z/,
    #     message: "only allows letters" }

    validates :salary,presence: true, format: { with: /\A[0-9.]+\z/,
        message: "only allows numbers" }

    # validates :employment_status ,presence: true

    

    
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :email, :job, :salary, :employment_status,:team_id,:email_confirmation)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong><%= t 'pages.Employees.forms.name' %>: </strong>
    <%= employee.name %>
  </p>

  <p>
    <strong><%= t 'pages.Employees.forms.email' %>: </strong>
    <%= employee.email %>
  </p>

  <p>
    <strong><%= t 'pages.Employees.forms.job' %>: </strong>
    <%= employee.job %>
  </p>

  <p>
    <strong><%= t 'pages.Employees.forms.salary' %>: </strong>
    <%= employee.salary %>
  </p>

  <p>
    <strong><%= t 'pages.Employees.forms.employment status' %>: </strong>
    <%= employee.employment_status %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= t('global.messages.error message',count: employee.errors.count) %></h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div>
    <%= form.label t('pages.Employees.forms.name', default: 'Name'), style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label t('pages.Employees.forms.email', default: 'Email'), style: "display: block" %>
    <%= form.text_field :email %>
  </div>


  <div>
    <%= form.label t('pages.Employees.forms.email confirmation', default: 'Email Confirmation') , style: "display: block" %>
    <%= form.text_field :email_confirmation %>
  </div>

  <div>
    <%= form.label t('pages.Employees.forms.job', default: 'Job'), style: "display: block" %>
    <%= form.text_field :job %>
  </div>

  <div>
    <%= form.label t('pages.Employees.forms.salary', default: 'Salary'), style: "display: block" %>
    <%= form.text_field :salary %>
  </div>

  <div>
    <%= form.label t('pages.Employees.forms.employment status', default: 'Status'), style: "display: block" %>
    <%= form.text_field :employment_status %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1><%= t('pages.Employees.forms.editing employee') %></h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to t('pages.Employees.buttons.show employee'), @employee %> |
  <%= link_to t('pages.Employees.buttons.back to employees'), employees_path %>
</div>

app/views/employees/index.html.erb
<div class="container">
<h1 class="text-center mt-5"><%= t 'models.Employees' %></h1>
 <a href="/" class="mt-5">&#8592; <%= t 'global.buttons.back to home' %></a>



<a href="/employees/new">
<span style="font-size: 48px; color: Dodgerblue;" class="d-block mt-3">
<i class="fas fa-plus-circle"></i>
</span>
</a>

   <table class="table table-hover">
    <thead class="table-info">
      <tr>
       <th><%= t 'pages.Employees.forms.id' %></th>
        <th><%= t 'pages.Employees.forms.name' %></th>
        <th><%= t 'pages.Employees.forms.email' %></th>
        <th><%= t 'pages.Employees.forms.job' %></th>
        <th><%= t 'pages.Employees.forms.salary' %></th>
        <th><%= t 'pages.Employees.forms.team' %></th>
        <th><%= t 'pages.Employees.forms.employment status' %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
     <% @employees.each do |employee| %>
      <tr>
        <td># <%=employee.id%></td>
        <td><%=employee.name%></td>
        <td><%=employee.email%></td>
        <td><%=employee.job%></td>
        <td><%=employee.salary%></td>
        <% if !(employee.team_id).nil? %>
        <td> <%=Team.find(employee.team_id).name %></td> 
        <%else%> <td></td> <%end%>
        <td><%=employee.employment_status%></td>
        <td class="px-0"><%= link_to t('global.buttons.show'), employee_path(employee), class: "btn btn-success"  %></td>
        <td class="px-0"><%= link_to t('global.buttons.edit'), edit_employee_path(employee), class: "btn btn-primary"  %></td>
        <td class="px-0"><%= button_to t('global.buttons.delete'), employee_path(employee), method: :delete, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
 

</div>

app/views/employees/new.html.erb
<h1><%= t('pages.Employees.forms.new employee') %></h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to t('pages.Employees.buttons.back to employees'), employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to t('pages.Employees.buttons.edit employee'), edit_employee_path(@employee) %> |
  <%= link_to t('pages.Employees.buttons.back to employees'), employees_path %>

  <%= button_to t('pages.Employees.buttons.destroy employee'), @employee, method: :delete %>
</div>