config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'
  resources :targets
  resources :divisions
  resources :teams
  resources :employees
  resources :users do
    member do
      delete :purge_picture
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'home/index'
  # get '/:locale' => 'home#index'
  root :to => "home#index"

end

app/models/target.rb
class Target < ApplicationRecord
    belongs_to :team, optional: true

    validates :title,length: { in: 3..20 },presence: true, format: { with: /\A[a-zA-Z0-9-]+\z/,
        message: "only allows letters, numbers and -" }

    validates :description,length: { maximum: 50 }

    validates_comparison_of :start_date, less_than: :finish_date

    # def start_must_be_before_finish_time
    #     errors.add(:start_time, "must be before finish time") unless
    #         start_time < finish_time
    # end 

end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /targets or /targets.json
  def index
    @targets = Target.all
  end

  # GET /targets/1 or /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets or /targets.json
  def create
    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to target_url(@target), notice: "Target was successfully created." }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1 or /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to target_url(@target), notice: "Target was successfully updated." }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1 or /targets/1.json
  def destroy
    @target.destroy

    respond_to do |format|
      format.html { redirect_to targets_url, notice: "Target was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def target_params
      params.require(:target).permit(:title, :description, :start_date, :finish_date, :status, :team_id)
    end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<%= form_with(model: target) do |form| %>
  <% if target.errors.any? %>
    <div style="color: red">
      <h2><%= t('global.messages.error message',count: target.errors.count) %></h2>

      <ul>
        <% target.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label t('pages.Targets.forms.title', default: 'Title'), style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label t('pages.Targets.forms.description', default: 'Description'), style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label t('pages.Targets.forms.start date', default: 'Start Date'), style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label t('pages.Targets.forms.finish date', default: 'Finish Date'), style: "display: block" %>
    <%= form.datetime_field :finish_date %>
  </div>

  <div>
    <%= form.label t('pages.Targets.forms.status', default: 'Status'), style: "display: block" %>
    <%= form.text_field :status %>
  </div>

<div>
    <%= form.label t('pages.Targets.forms.team', default: 'Team'), style: "display: block" %>
    <%= form.select :team_id, Team.all.collect{ |team| [team.name,team.id] }%>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/targets/_target.html.erb
<div id="<%= dom_id target %>">
  <p>
    <strong><%= t 'pages.Targets.forms.title' %>: </strong>
    <%= target.title %>
  </p>

  <p>
    <strong><%= t 'pages.Targets.forms.description' %>: </strong>
    <%= target.description %>
  </p>

  <p>
    <strong><%= t 'pages.Targets.forms.start date' %>: </strong>
    <%= target.start_date %>
  </p>

  <p>
    <strong><%= t 'pages.Targets.forms.finish date' %>: </strong>
    <%= target.finish_date %>
  </p>

  <p>
    <strong><%= t 'pages.Targets.forms.status' %>: </strong>
    <%= target.status %>
  </p>

</div>

app/views/targets/edit.html.erb
<h1><%= t('pages.Targets.forms.editing target') %></h1>

<%= render "form", target: @target %>

<br>

<div>
  <%= link_to t('pages.Targets.buttons.show target'), @target %> |
 <%= link_to t('pages.Targets.buttons.back to targets'), targets_path %>
</div>

app/views/targets/index.html.erb
<div class="container">
<h1 class="text-center mt-5"><%= t 'models.Targets' %></h1>
 <a href="/" class="mt-5">&#8592; <%= t 'global.buttons.back to home' %></a>



<a href="/targets/new">
<span style="font-size: 48px; color: Dodgerblue;" class="d-block mt-3">
<i class="fas fa-plus-circle"></i>
</span>
</a>

   <table class="table table-hover">
    <thead class="table-info">
      <tr>
      <th><%= t 'pages.Targets.forms.id' %></th>
       <th><%= t 'pages.Targets.forms.title' %></th>
        <th><%= t 'pages.Targets.forms.description' %></th>
        <th><%= t 'pages.Targets.forms.start date' %></th>
        <th><%= t 'pages.Targets.forms.finish date' %></th>
        <th><%= t 'pages.Targets.forms.status' %></th>
        <th><%= t 'pages.Targets.forms.team' %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
     <% @targets.each do |target| %>
      <tr>
        <td># <%=target.id%></td>
        <td><%=target.title%></td>
        <td><%=target.description%></td>
        <td><%= target.start_date %></td>
        <td><%= target.finish_date %></td>
        <td><%=target.status%></td>
        <% if !(target.team_id).nil? %>
        <td> <%=Team.find(target.team_id).name %></td> 
        <%else%><td></td> <%end%>
       <td class="px-0"><%= link_to t('global.buttons.show'), target_path(target), class: "btn btn-success"  %></td>
        <td class="px-0"><%= link_to t('global.buttons.edit'), edit_target_path(target), class: "btn btn-primary"  %></td>
        <td class="px-0"><%= button_to t('global.buttons.delete'), target_path(target), method: :delete, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
 

</div>

app/views/targets/new.html.erb
<h1><%= t('pages.Targets.forms.new target') %></h1>

<%= render "form", target: @target %>

<br>

<div>
  <%= link_to t('pages.Targets.buttons.back to targets'), targets_path %>
</div>

app/views/targets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @target %>

<div>
  <%= link_to t('pages.Targets.buttons.edit target'), edit_target_path(@target) %> |
   <%= link_to t('pages.Targets.buttons.back to targets'), targets_path %>

  <%= button_to t('pages.Targets.buttons.destroy target'), @target, method: :delete %>
</div>