config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'
  resources :targets
  resources :divisions
  resources :teams
  resources :employees
  resources :users do
    member do
      delete :purge_picture
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'home/index'
  # get '/:locale' => 'home#index'
  root :to => "home#index"

end

app/models/division.rb
class Division < ApplicationRecord
    belongs_to :employee, optional: true
    has_many :teams, dependent: :destroy
    # after_save :update_teams
    # serialize :teams

    # def update_teams
    #     teams.each do |team|
    #         team.update(:id => team.id)
    #     end
    # end

    validates :name,length: { in: 3..20 },presence: true, format: { with: /\A[a-zA-Z0-9-]+\z/,
        message: "only allows letters, numbers and -" }

    validates :description,length: { maximum: 50 }

    validates :employee_id, presence: true,uniqueness: true

    validates :teams, presence: true


end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /divisions or /divisions.json
  def index
    @divisions = Division.all
    # @division = Division.find(params[:id])
  
    # @teams=[]
    # @divs_teams=[]
    # @divisions.each do |division|
    #   division.teams.each{|team|  @teams.push(team.id) }
    #   @divs_teams.push(@teams)
    #   @teams=[]
    # end


  end



  # GET /divisions/1 or /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions or /divisions.json
  def create

    
    if !(division_params["teams"]).nil? 
      division_teams = division_params["teams"].map{|team| Team.find(team.to_i)}
      d_p = division_params
      d_p["teams"] = division_teams
      @division = Division.new(d_p)
    else
      @division = Division.new(division_params)
    end

    respond_to do |format|
      if @division.save
        format.html { redirect_to division_url(@division), notice: "Division was successfully created." }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1 or /divisions/1.json
  def update
    # @division.teams.push(@teams)
   
    # division_name = params["division"]["name"]
    # division_teams = division_params["teams"].map{|team| Team.find(team.to_i)}
    # division_params["teams"] = division_teams
    # d_p = division_params
    # d_p["teams"] = division_teams
    # p "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
    # p d_p
    # p "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
    # @division.update(teams: division_teams)


    d_p = division_params

    if !(division_params["teams"]).nil? 
      division_teams = division_params["teams"].map{|team| Team.find(team.to_i)}
      d_p["teams"] = division_teams
    end


    respond_to do |format|
      if @division.update(d_p)

        format.html { redirect_to division_url(@division), notice: "Division was successfully updated." }
        format.json { render :show, status: :ok, location: @division }

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1 or /divisions/1.json
  def destroy
    @division.destroy
    respond_to do |format|
      format.html { redirect_to divisions_url, notice: "Division was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def division_params
      params.require(:division).permit(:name, :description, :employee_id,:teams => [])
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_division.html.erb
<div id="<%= dom_id division %>">
  <p>
    <strong><%= t('pages.Divisions.forms.name') %>: </strong>
    <%= division.name %>
  </p>

  <p>
    <strong><%= t('pages.Divisions.forms.description') %>: </strong>
    <%= division.description %>
  </p>

  <p>
    <strong><%= t('pages.Divisions.forms.manager') %>: </strong>
    <%= division.employee_id %>
  </p>

    <p>
    <strong><%= t('pages.Divisions.forms.teams') %>: </strong>
    <%= division.teams.collect(&:name).join(',') %>
  </p>

</div>

app/views/divisions/_form.html.erb
<%= form_with(model: division) do |form| %>
  <% if division.errors.any? %>
    <div style="color: red">
      <h2><%= t('global.messages.error message',count: division.errors.count) %></h2>

      <ul>
        <% division.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label t('pages.Divisions.forms.name', default: 'Name'), style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label t('pages.Divisions.forms.description', default: 'Description'), style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label t('pages.Divisions.forms.manager', default: 'Manager'), style: "display: block" %>
    <%= form.select :employee_id, Employee.all.collect{ |employee| [employee.name,employee.id] }%>
  </div>

 <div>
    <%= form.label t('pages.Divisions.forms.teams', default: 'Teams'), style: "display: block" %>
   <%# <%= form.select :teams, Team.all.collect { |team| ["##{team.id}", team] },{:include_hidden => false},{ :multiple => true, class: 'selectpicker'} %> 
   <%= form.select :teams, Team.all.collect{ |team| [team.name,team.id] },{:include_hidden => false, selected: @division.teams.map(&:id)},{ :multiple => true, :class => 'p-1 pr-5'} %> 

  </div>

 <!--  <div>

  <%= form.label "Teams", style: "display: block" %>
  <%= form.select :teams, 
                   options_from_collection_for_select(Team.all, :id, :name, @division.teams.map(&:id)),{:include_hidden => false},
    { :multiple => true, :class => 'p-1 pr-5'} %>

  </div> -->

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1><%= t('pages.Divisions.forms.editing division') %></h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to t('pages.Divisions.buttons.show division'), @division %> |
  <%= link_to t('pages.Divisions.buttons.back to divisions'), divisions_path %>
</div>

app/views/divisions/index.html.erb
<div class="container">
<h1 class="text-center mt-5"><%= t 'models.Divisions' %></h1>
 <a href="/" class="mt-5">&#8592; <%= t 'global.buttons.back to home' %></a>



<a href="/divisions/new">
<span style="font-size: 48px; color: Dodgerblue;" class="d-block mt-3">
<i class="fas fa-plus-circle"></i>
</span>
</a>

   <table class="table table-hover">
    <thead class="table-info">
      <tr>
       <th><%= t 'pages.Divisions.forms.id' %></th>
        <th><%= t 'pages.Divisions.forms.name' %></th>
        <th><%= t 'pages.Divisions.forms.description' %></th>
        <th><%= t 'pages.Divisions.forms.teams' %></th>
        <th><%= t 'pages.Divisions.forms.manager' %></th>
        <th></th>
         <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
     <% @divisions.each do |division| %>
      <tr>
        <td># <%=division.id%></td>
        <td><%=division.name%></td>
        <td><%=division.description%></td>
        <td><p class="overme"><%= division.teams.collect(&:name).join(',') %></p></td>

        <% if !(division.employee).nil? %>
        <td> <%=Employee.find(division.employee_id).name %></td> 
        <%else%> <td></td> <%end%>

       <td class="px-0"><%= link_to t('global.buttons.show'), division_path(division), class: "btn btn-success"  %></td>
       <td class="px-0"><%= link_to t('global.buttons.edit'), edit_division_path(division), class: "btn btn-primary"  %></td>
       <td class="px-0"><%= button_to t('global.buttons.delete'), division_path(division), method: :delete, class: "btn btn-danger"  %></td>


      </tr>
    <% end %>
    </tbody>
  </table>
 

</div>

app/views/divisions/new.html.erb
<h1><%= t('pages.Divisions.forms.new division') %></h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to t('pages.Divisions.buttons.back to divisions'), divisions_path %>
</div>

app/views/divisions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @division %>

<div>
  <%= link_to t('pages.Divisions.buttons.edit division'), edit_division_path(@division) %> |
  <%= link_to t('pages.Divisions.buttons.back to divisions'), divisions_path %>

  <%= button_to t('pages.Divisions.buttons.destroy division'), @division, method: :delete %>
</div>