config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'
  resources :targets
  resources :divisions
  resources :teams
  resources :employees
  resources :users do
    member do
      delete :purge_picture
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'home/index'
  # get '/:locale' => 'home#index'
  root :to => "home#index"

end

app/views/layouts/_bottom_navigation.html.erb
<nav class="navbar border-bottom m-0">

  <ul class="align-items-center ml-auto m-0" style="list-style-type: none;">
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <i class="fal fa-globe text-dark fa-lg"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'English', url_for(locale: :en), class: "dropdown-item" %>
          <%= link_to 'عربي', url_for(locale: :ar), class: "dropdown-item" %>
        </div>
</li>
</ul>

</nav>

app/views/layouts/_footer.html.erb
 <footer id="sticky-footer" class="flex-shrink-0 py-3 bg-light text-black">
    <div class="container text-center">
      <small>Copyright &copy; - Sprints - author: ohoud , e-mail: oalyahyawi@mrsool.co</small>
    </div>
  </footer>

app/views/layouts/_side_navigation.html.erb
 <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-dark sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
               
                  <span data-feather="home"></span>
                   <%= link_to t('models.Dashboard', default: 'Dashboard'), home_index_path, class: "nav-link active" %>
                    <span class="sr-only">(current)</span>
            
              </li>
              <li class="nav-item">
          
                  <span data-feather="file"></span>
                  <%= link_to t('models.Users', default: 'Users'), users_path, class: "nav-link" %>
          
              </li>
              <li class="nav-item">
              
                  <span data-feather="shopping-cart"></span>
                  <%= link_to t('models.Employees', default: 'Employees'), employees_path, class: "nav-link" %>
           
              </li>
              <li class="nav-item">
            
                  <span data-feather="users"></span>
                 <%= link_to t('models.Teams', default: 'Teams'), teams_path, class: "nav-link" %>
            
              </li>
              <li class="nav-item">
           
                  <span data-feather="bar-chart-2"></span>
                  <%= link_to t('models.Divisions', default: 'Divisions'), divisions_path, class: "nav-link" %>
     
              </li>
              <li class="nav-item">
           
                  <span data-feather="layers"></span>
                  <%= link_to t('models.Targets', default: 'Targets'), targets_path, class: "nav-link" %>
      
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
         

app/views/layouts/_top_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarText">
   <span class="navbar-text">
      HR Admin Platform
    </span>

  <ul class="navbar-nav ml-auto align-items-center mr-5" style="list-style-type: none;">


  <% if !user_signed_in? %>
  <li class="nav-item"><%= link_to t('navbar.Sign In'), new_user_session_path, class:"btn btn-outline-success  mr-2 nav-link text-success" %></li>
  <li class="nav-item"><%= link_to t('navbar.Sign Up'), new_user_registration_path, class: "btn btn-sm btn-outline-secondary mr-2 nav-link text-secondary" %></li>
    
  <%else%>
  <span class="navbar-text px-4"><%= current_user.name %></span>
  <li class="nav-item"><%= button_to t('navbar.Sign Out'), destroy_user_session_path(@user), method: :delete , class:"btn btn-sm btn-outline-danger nav-link" %></li>
    
  <%end%>


</ul>



</div>
 


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html >
<html <% if I18n.locale.to_s == "ar"%> dir="rtl" <%end%>>
  <head>
    <title>HREmployeeSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="../../assets/stylesheets/application.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css"> %>
  </head>

  <body>



<nav class="navbar navbar-light bg-light">
<div class="container">
  <ul class="p-0 d-flex" style="list-style-type: none;">
  <% if !user_signed_in? %>
    <li><a><%= link_to t('navbar.Sign Up'), new_user_registration_path, class: "btn btn-outline-success mr-2" %></a></li>
    <li><a><%= link_to t('navbar.Sign In'), new_user_session_path, class:"btn btn-sm btn-outline-secondary mr-2" %></a></li>
  <%else%>
    <li><a><%= button_to t('navbar.Sign Out'), destroy_user_session_path(@user), method: :delete , class:"btn btn-sm btn-outline-danger" %></a></li>
  <%end%>
</ul>

<ul class="float-right" style="list-style-type: none;">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <i class="fal fa-globe text-dark fa-lg"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item"><%= link_to 'English', url_for(locale: :en) %></a>
          <a class="dropdown-item"><%= link_to 'عربي', url_for(locale: :ar) %></a>
        </div>
      </li>
</ul>
 

</div>

</nav>





<!-- Here is the sidebar -->
<!--
  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
  //  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> 
   <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav px-3 form-inline">
      <% if !user_signed_in? %>
        <li class="nav-item text-nowrap">
         <a class="nav-link"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link btn btn-outline-success mr-2" %></a>
        </li>
        <li class="nav-item text-nowrap">
         <a class="nav-link"><%= link_to "Sign In", new_user_session_path, class:"nav-link btn btn-sm btn-outline-secondary mr-2" %></a>
        </li>
        <%else%>
        <li class="nav-item text-nowrap">
        <a class="nav-link"><%= button_to "Sign Out", destroy_user_session_path(@user), method: :delete , class:"btn btn-sm btn-outline-danger" %></a>
     </li>
      <%end%>
      </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file"></span>
                  Orders
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="shopping-cart"></span>
                  Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="users"></span>
                  Customers
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reports
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                  Integrations
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

-->
<!-- Here is the sidebar -->

<div class="container">
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= yield %>
</div>
<!--
 </main>
      </div>
    </div>
-->

  </body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
<%# <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<script type="text/javascript">


</script>
 %>

<%# <script type="text/javascript">
 $('#myModal').on('shown.bs.modal', function () {
  $('#myInput').trigger('focus')
})
</script> %>

<!-- Icons -->
<!--
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
  -->

    <!-- Graphs -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.1/dist/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
-->





</html>